Vagrant.configure("2") do |config|
  (1..3).each do |i|
    config.vm.define "mac#{i}" do |mac|
      mac.vm.box = "ubuntu/bionic64"
      if i == 1
        mac.vm.network "private_network", ip: "192.168.50.1#{i}"
      elsif i == 2
        mac.vm.network "private_network", ip: "192.168.50.254"
        mac.vm.network "private_network", ip: "10.0.0.254"
      elsif i = 3
        mac.vm.network "private_network", ip: "10.0.0.#{i}"
      end
      mac.vm.provider "virtualbox" do |vb|
        vb.memory = 512
      end

      mac.vm.provision "shell", path: "route#{i}.sh"
    end
  end
end
