# -*- mode: ruby -*-
# vi: set ft=ruby :

# Defina a imagem base para as máquinas virtuais
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  # Configuração da primeira máquina virtual
  config.vm.define "luiz" do |vm1|
    vm1.vm.network "private_network", type: "dhcp"
    vm1.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = "2"
    end
    config.vm.provision "shell",  path: "configuracoes.sh"
  end

  # Configuração da segunda máquina virtual
  config.vm.define "uigor" do |vm2|
  vm2.vm.network "private_network", type: "dhcp"
  vm2.vm.provider "virtualbox" do |vb|
  vb.memory = "512"
  vb.cpus = "2"
    end
    config.vm.provision "shell", path: "configuracoes.sh"
  end
end